name = "notebook-wiki-cf"
pages_build_output_dir = "./dist"
compatibility_date = "2025-08-15"
compatibility_flags = ["nodejs_compat", "enable_nodejs_http_server_modules"]

[[r2_buckets]]
binding = "NOTEBOOK_WIKI_R2"
bucket_name = "notebook-wiki-r2"
