/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface User {
  id: string;
  username: string;
  totpSecret: string;
  apiKey: string;
  createdAt: string;
  aiProvider?: "gemini" | "openai-compatible";
  aiApiKey?: string;
  aiEndpoint?: string;
  aiModel?: string;
  theme?: string;
}

export interface Memo {
  id: string;
  userId: string;
  title: string;
  content: string; // Plaintext when sent to/from frontend during active session, stored encrypted on server
  tags: string[]; // Always exactly 5 tags generated by Gemini or user
  relatedMemoIds: string[]; // Connected memo IDs
  summary?: string; // Japanese summary of memo content
  createdAt: string;
  updatedAt: string;
  googleFileId?: string;
  googleFileName?: string;
}

export interface GraphNode {
  id: string;
  title: string;
  tags: string[];
  type?: "memo" | "tag";
}

export interface GraphLink {
  source: string;
  target: string;
}

export interface GraphData {
  nodes: GraphNode[];
  links: GraphLink[];
}

export interface UserSession {
  userId: string;
  username: string;
  apiKey: string;
  token: string;
}
